# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 725a8994a7d70867d68c3f9afff1d95424329cd7e6c7d86ff10057eb91d724c74a1e791fa081265a439b9828bf86b48406924bd7416f965959bad8653ced838b

test:
  secret_key_base: acb8db640eedd9083bb6352d03c57c814411913c082e2448e8ec62c6f8a0c7bd755a56527f2d5c920970c88fc0c6f4a0d26d0daa9ef00b26a52a69c2c2d9406f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>